// <auto-generated />
using CountriesAPI.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace CountriesAPI.Migrations
{
    [DbContext(typeof(CountryStateContext))]
    [Migration("20260217064109_initial")]
    partial class initial
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.24")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("CountriesAPI.Models.Country", b =>
                {
                    b.Property<int>("CId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CId"));

                    b.Property<string>("CCode")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<string>("CName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("CId");

                    b.ToTable("Countries");

                    b.HasData(
                        new
                        {
                            CId = 1,
                            CCode = "IND",
                            CName = "India"
                        },
                        new
                        {
                            CId = 2,
                            CCode = "AUS",
                            CName = "Australia"
                        });
                });

            modelBuilder.Entity("CountriesAPI.Models.State", b =>
                {
                    b.Property<int>("SId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("SId"));

                    b.Property<int>("CntryId")
                        .HasColumnType("int");

                    b.Property<string>("SName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("SId");

                    b.HasIndex("CntryId");

                    b.ToTable("States");

                    b.HasData(
                        new
                        {
                            SId = 1,
                            CntryId = 1,
                            SName = "Odisha"
                        },
                        new
                        {
                            SId = 2,
                            CntryId = 1,
                            SName = "Delhi"
                        },
                        new
                        {
                            SId = 3,
                            CntryId = 2,
                            SName = "New South Wales"
                        });
                });

            modelBuilder.Entity("CountriesAPI.Models.State", b =>
                {
                    b.HasOne("CountriesAPI.Models.Country", "Country")
                        .WithMany("States")
                        .HasForeignKey("CntryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Country");
                });

            modelBuilder.Entity("CountriesAPI.Models.Country", b =>
                {
                    b.Navigation("States");
                });
#pragma warning restore 612, 618
        }
    }
}
